/**
 * usePresence
 *
 * Supabase Realtime Presence channel for the Loop feed.
 * Tracks who is currently browsing the app or inside a room.
 *
 * Each client tracks its own state on mount and untracks on unmount.
 * The `sync` event fires whenever any user joins or leaves, keeping
 * the local list of online users current.
 *
 * Presence payload shape:
 *   {
 *     user_id:      string
 *     display_name: string | null
 *     avatar_url:   string | null
 *     status:       'browsing' | 'in_room'
 *     room_id?:     string        // only when status = 'in_room'
 *     room_title?:  string        // only when status = 'in_room'
 *   }
 */
import { useCallback, useEffect, useRef, useState } from 'react';
import type { RealtimeChannel } from '@supabase/supabase-js';
import { supabase, authedSupabase } from '@/lib/supabase';
import { getToken } from '@/lib/storage';

export type PresenceUser = {
  user_id:      string;
  display_name: string | null;
  avatar_url:   string | null;
  status:       'browsing' | 'in_room';
  room_id?:     string;
  room_title?:  string;
  /** Unique key generated by Supabase (presence_ref) */
  presenceRef:  string;
};

type TrackPayload = Omit<PresenceUser, 'presenceRef'>;

type PresenceState = Record<string, Array<{ presence_ref: string } & TrackPayload>>;

export function usePresence(selfPayload: TrackPayload | null) {
  const [online,    setOnline]    = useState<PresenceUser[]>([]);
  const [connected, setConnected] = useState(false);
  const channelRef = useRef<RealtimeChannel | null>(null);

  useEffect(() => {
    if (!selfPayload) return;
    let cancelled = false;

    async function setup() {
      const token  = await getToken();
      const client = token ? await authedSupabase(token) : supabase;

      const channel = client.channel('loop:presence:feed', {
        config: { presence: { key: selfPayload.user_id } },
      });

      channel
        .on('presence', { event: 'sync' }, () => {
          if (cancelled) return;
          const state = channel.presenceState<TrackPayload>();
          const users = buildUserList(state, selfPayload.user_id);
          setOnline(users);
        })
        .on('presence', { event: 'join' }, ({ newPresences }) => {
          // sync fires too, but join gives us a chance to animate in
        })
        .on('presence', { event: 'leave' }, ({ leftPresences }) => {
          // sync fires too
        })
        .subscribe(async (status) => {
          if (status === 'SUBSCRIBED' && !cancelled) {
            await channel.track(selfPayload);
            setConnected(true);
          }
        });

      channelRef.current = channel;
    }

    setup();
    return () => {
      cancelled = true;
      channelRef.current?.untrack();
      channelRef.current?.unsubscribe();
      channelRef.current = null;
      setConnected(false);
      setOnline([]);
    };
  }, [selfPayload?.user_id, selfPayload?.status, selfPayload?.room_id]);

  /** Call this when the user enters a room to update their presence */
  const setInRoom = useCallback(async (roomId: string, roomTitle: string) => {
    if (!selfPayload || !channelRef.current) return;
    await channelRef.current.track({
      ...selfPayload,
      status:     'in_room',
      room_id:    roomId,
      room_title: roomTitle,
    });
  }, [selfPayload]);

  /** Call this when the user leaves a room */
  const setBrowsing = useCallback(async () => {
    if (!selfPayload || !channelRef.current) return;
    await channelRef.current.track({
      ...selfPayload,
      status:    'browsing',
      room_id:   undefined,
      room_title: undefined,
    });
  }, [selfPayload]);

  return { online, connected, setInRoom, setBrowsing };
}

// ── Helpers ──────────────────────────────────────────────────────────

function buildUserList(state: PresenceState, selfId: string): PresenceUser[] {
  const users: PresenceUser[] = [];
  for (const [, presences] of Object.entries(state)) {
    for (const p of presences) {
      // Exclude self from the displayed list
      if (p.user_id === selfId) continue;
      users.push({
        user_id:      p.user_id,
        display_name: p.display_name ?? null,
        avatar_url:   p.avatar_url ?? null,
        status:       p.status ?? 'browsing',
        room_id:      p.room_id,
        room_title:   p.room_title,
        presenceRef:  p.presence_ref,
      });
    }
  }
  // Sort: in_room first, then browsing; alphabetical within each group
  return users.sort((a, b) => {
    if (a.status === b.status) {
      return (a.display_name ?? '').localeCompare(b.display_name ?? '');
    }
    return a.status === 'in_room' ? -1 : 1;
  });
}
